### ISSUE TITLE
Error in windows 10

### ISSUE THREAD

**Issue by dvdrbls** [fabrizioromanelli/ladyEntropy#1]
Hi, I tried to compile it using msys2 and I got this error

$ g++ rose.c++ -lglut -lGL -o rose
rose.c++:4:10: fatal error: GL/freeglut.h: No such file or directory
    4 | #include "GL/freeglut.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated

I already installed manually this package both versions 86 & 64, what am I doing wrong?
thanks!

**Comment by fabrizioromanelli** [comment]
@dvdrbls I haven't tried to compile it on Windows 10. However I think it should be quite straightforward using msys2 framework. I'm not an expert of msys2 but I think you should check the freeglut directories to let `g++` understand where the header files and libraries are located. In the console environment where you are trying to compile, you could check for the environment variables to see if the paths are correct for `freeglut.h`.
When you say "I already installed manually this package both versions 86 & 64", which package are you referring to?

**Comment by dvdrbls** [comment]
Hi!

didnt work again, this is the latest output on my machine

C:\Users\Dell\Desktop>cd ladyentropy

C:\Users\Dell\Desktop\ladyEntropy>g++ rose.c++ -lglut -lGL -o rose
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lglut
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lGL
collect2.exe: error: ld returned 1 exit status

C:\Users\Dell\Desktop\ladyEntropy>g++ lady_entropy.c++ -lglut -lGL -o lentroy
In file included from lady_entropy.c++:29:
includes/typedefs.hpp:1:13: error: conflicting declaration 'typedef int LONG'
    1 | typedef int LONG;
      |             ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:287:20: note: previous declaration as 'typedef long int LONG'
  287 |   typedef __LONG32 LONG;
      |                    ^~~~
In file included from lady_entropy.c++:29:
includes/typedefs.hpp:3:22: error: conflicting declaration 'typedef unsigned int DWORD'
    3 | typedef unsigned int DWORD;
      |                      ^~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:141:29: note: previous declaration as 'typedef long unsigned int DWORD'
  141 |   typedef unsigned __LONG32 DWORD;
      |                             ^~~~~
In file included from lady_entropy.c++:29:
includes/typedefs.hpp:5:16: error: redefinition of 'struct tagBITMAPFILEHEADER'
    5 | typedef struct tagBITMAPFILEHEADER {
      |                ^~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:71,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/wingdi.h:684:18: note: previous definition of 'struct tagBITMAPFILEHEADER'
  684 |   typedef struct tagBITMAPFILEHEADER {
      |                  ^~~~~~~~~~~~~~~~~~~
In file included from lady_entropy.c++:29:
includes/typedefs.hpp:11:27: warning: 'packed' attribute ignored [-Wattributes]
   11 | } __attribute__((packed)) BITMAPFILEHEADER;
      |                           ^~~~~~~~~~~~~~~~
includes/typedefs.hpp:11:27: error: conflicting declaration 'typedef int BITMAPFILEHEADER'
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:71,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/wingdi.h:690:5: note: previous declaration as 'typedef struct tagBITMAPFILEHEADER BITMAPFILEHEADER'
  690 |   } BITMAPFILEHEADER,*LPBITMAPFILEHEADER,*PBITMAPFILEHEADER;
      |     ^~~~~~~~~~~~~~~~
In file included from lady_entropy.c++:29:
includes/typedefs.hpp:13:16: error: redefinition of 'struct tagBITMAPINFOHEADER'
   13 | typedef struct tagBITMAPINFOHEADER {
      |                ^~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:71,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/wingdi.h:593:18: note: previous definition of 'struct tagBITMAPINFOHEADER'
  593 |   typedef struct tagBITMAPINFOHEADER {
      |                  ^~~~~~~~~~~~~~~~~~~
In file included from lady_entropy.c++:29:
includes/typedefs.hpp:25:27: warning: 'packed' attribute ignored [-Wattributes]
   25 | } __attribute__((packed)) BITMAPINFOHEADER;
      |                           ^~~~~~~~~~~~~~~~
includes/typedefs.hpp:25:27: error: conflicting declaration 'typedef int BITMAPINFOHEADER'
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:71,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/wingdi.h:605:5: note: previous declaration as 'typedef struct tagBITMAPINFOHEADER BITMAPINFOHEADER'
  605 |   } BITMAPINFOHEADER,*LPBITMAPINFOHEADER,*PBITMAPINFOHEADER;
      |     ^~~~~~~~~~~~~~~~
lady_entropy.c++:37:7: error: 'float SIZE' redeclared as different kind of entity
   37 | float SIZE  = 0.0;
      |       ^~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/include/GL/freeglut_std.h:63,
                 from C:/msys64/mingw64/include/GL/freeglut.h:17,
                 from lady_entropy.c++:20:
C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:104:3: note: previous declaration 'typedef struct tagSIZE SIZE'
  104 | } SIZE,*PSIZE,*LPSIZE;
      |   ^~~~
lady_entropy.c++: In function 'void drawArt()':
lady_entropy.c++:171:12: error: expected unqualified-id before '>' token
  171 |   if (SIZE > 0.0) {
      |            ^
lady_entropy.c++:172:21: error: expected primary-expression before ';' token
  172 |     cube_size = SIZE;
      |                     ^
lady_entropy.c++: In function 'int main(int, char**)':
lady_entropy.c++:287:14: error: expected unqualified-id before '=' token
  287 |         SIZE = v;
      |              ^
lady_entropy.c++:307:15: error: 'GL_MULTISAMPLE' was not declared in this scope; did you mean 'GLUT_MULTISAMPLE'?
  307 |     glDisable(GL_MULTISAMPLE);
      |               ^~~~~~~~~~~~~~
      |               GLUT_MULTISAMPLE
lady_entropy.c++:312:14: error: 'GL_MULTISAMPLE' was not declared in this scope; did you mean 'GLUT_MULTISAMPLE'?
  312 |     glEnable(GL_MULTISAMPLE);
      |              ^~~~~~~~~~~~~~
      |              GLUT_MULTISAMPLE

**Comment by fabrizioromanelli** [comment]
> Hi!
> 
> didnt work again, this is the latest output on my machine
> 
> C:\Users\Dell\Desktop>cd ladyentropy
> 
> C:\Users\Dell\Desktop\ladyEntropy>g++ rose.c++ -lglut -lGL -o rose
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lglut
> C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lGL
> collect2.exe: error: ld returned 1 exit status

Try to compile as follows:
`g++ rose.c++ -lfreeglut -lopengl32 -o rose`
In Windows it should solve the problem, but you have to read this walkthrough [here](https://www.transmissionzero.co.uk/computing/using-glut-with-mingw/).

I've also updated the `typedefs.hpp` with a new version to fix few issues, so please do a `git pull` from master branch and try again the following.

Do the same with `lady_entropy.c`:
`g++ lady_entropy.c++ -lfreeglut -lopengl32 -o lentroy`

**Comment by dvdrbls** [comment]
Thanks! only the rose worked that way, but thats ok Ill comeback to this example once I have more experience

**Comment by fabrizioromanelli** [comment]
@dvdrbls no problem and happy to help!
